#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

INSTALLER_LIST=$(find . -maxdepth 2 -name install.sh)
# -u 9: use a different file descriptor as otherwise the loop can break if a
# script also uses stdin
while IFS= read -r -u 9 installer
do
    echo "Run '${installer}'"
    sh -c "${installer}"
    echo "'${installer}' finished with exit code: $?"
    echo "Executed '${installer}'"
done 9<<< "${INSTALLER_LIST}"
